-- Migration: Create cards table
-- Description: Create a table to store birthday cards generated by users
-- Date: 2026-02-15

-- Create cards table
CREATE TABLE IF NOT EXISTS cards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    person_name VARCHAR(255) NOT NULL,
    greeting_text TEXT NOT NULL,
    template_id VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on user_id for faster queries
CREATE INDEX IF NOT EXISTS idx_cards_user_id ON cards(user_id);

-- Create index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_cards_created_at ON cards(created_at DESC);

-- Enable RLS (Row Level Security) on cards table
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

-- Create RLS policy: Users can only see their own cards
CREATE POLICY "Users can view their own cards" 
    ON cards FOR SELECT 
    USING (auth.uid() = user_id);

-- Create RLS policy: Users can only insert cards for themselves
CREATE POLICY "Users can insert their own cards" 
    ON cards FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

-- Create RLS policy: Users can only update their own cards
CREATE POLICY "Users can update their own cards" 
    ON cards FOR UPDATE 
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Create RLS policy: Users can only delete their own cards
CREATE POLICY "Users can delete their own cards" 
    ON cards FOR DELETE 
    USING (auth.uid() = user_id);

-- Grant permissions to authenticated users
GRANT SELECT, INSERT, UPDATE, DELETE ON cards TO authenticated;
GRANT USAGE ON SEQUENCE cards_id_seq TO authenticated;
